USE bank_fraud_db;

-- 1. ROW COUNT HAR TABLE KA
SELECT 'BRANCH'             AS Table_Name, COUNT(*) AS Row_Count FROM BRANCH
UNION ALL
SELECT 'CUSTOMER',           COUNT(*) FROM CUSTOMER
UNION ALL
SELECT 'ACCOUNT',            COUNT(*) FROM ACCOUNT
UNION ALL
SELECT 'TRANSACTION',        COUNT(*) FROM TRANSACTION
UNION ALL
SELECT 'INVESTIGATOR',       COUNT(*) FROM INVESTIGATOR
UNION ALL
SELECT 'FRAUD_ALERT',        COUNT(*) FROM FRAUD_ALERT
UNION ALL
SELECT 'INVESTIGATION_CASE', COUNT(*) FROM INVESTIGATION_CASE
UNION ALL
SELECT 'BLACKLIST',          COUNT(*) FROM BLACKLIST;

-- 2. NULL CHECK
SELECT Customer_ID, Full_Name, CNIC, Email
FROM CUSTOMER
WHERE Full_Name IS NULL OR CNIC IS NULL OR Email IS NULL;

-- 3. FK CHECK — TRANSACTION ka ACCOUNT exist karta hai?
SELECT t.Transaction_ID
FROM TRANSACTION t
LEFT JOIN ACCOUNT a ON t.Account_ID = a.Account_ID
WHERE a.Account_ID IS NULL;

-- 4. FK CHECK — FRAUD_ALERT ka TRANSACTION exist karta hai?
SELECT fa.Alert_ID
FROM FRAUD_ALERT fa
LEFT JOIN TRANSACTION t ON fa.Transaction_ID = t.Transaction_ID
WHERE t.Transaction_ID IS NULL;

-- 5. DUPLICATE CNIC CHECK
SELECT CNIC, COUNT(*) AS Count
FROM CUSTOMER
GROUP BY CNIC
HAVING COUNT(*) > 1;

-- 6. BLACKLISTED CUSTOMERS
SELECT b.Blacklist_ID, c.Full_Name, c.CNIC, b.Reason, b.Date_Added, b.Added_By
FROM BLACKLIST b
JOIN CUSTOMER c ON b.Customer_ID = c.Customer_ID;

-- 7. OPEN CASES WITH INVESTIGATOR
SELECT ic.Case_ID, ic.Case_Status, ic.Date_Opened,
       fa.Alert_Type, fa.Priority,
       i.Full_Name AS Investigator
FROM INVESTIGATION_CASE ic
JOIN FRAUD_ALERT  fa ON ic.Alert_ID        = fa.Alert_ID
JOIN INVESTIGATOR i  ON ic.Investigator_ID = i.Investigator_ID
WHERE ic.Case_Status != 'Closed';